### PR TITLE
Use deployment instead of statefulset

### PR DESCRIPTION
**Pull request by mehdicopter**
- Create new labels and templates
- Add possibility to create service account or not
- Use deployment instead of statefulset 
- Add Horizontal Pod Autoscaling

### CODE REVIEW

**Comment by renehernandez** [comment]
> * Use deployment instead of statefulset

`Deployments` objects are recommended for non-stateful applications. Meilisearch, as well as other DB, are stateful applications and are better served by a `StatefulSet` object.

>  * Horizontal Pod Autoscaling

Multiple replicas won't work at this moment since *Meilisearch* does not support replication

**Review by renehernandez — CHANGES_REQUESTED** [review]
> * Use deployment instead of statefulset

Deployments objects are recommended for non-stateful applications. Meilisearch, as well as other DB, are stateful applications and are better served by a StatefulSet object.

> * Horizontal Pod Autoscaling

Multiple replicas won't work at this moment since Meilisearch does not support replication

Please revert back to use a deployment and remove the hpa definition and values

**Comment by mehdicopter** [comment]
We could still attach an existing PVC to the deployment and "fix" the number of replicas to 1 ?

**Comment by renehernandez** [comment]
> We could still attach an existing PVC to the deployment and set the number of replicas to 1?

Using a statefulset have advantages beyond this:

* If the StatefulSet is deleted or scaled down, the associated volume will be preserved, which is important in the case of the database
* When Meilisearch supports multiple replicas, then the ordering of Pod during creation and deletion provided by the StatefulSet may be important for some initialization and cleanup procedures.

**Comment by renehernandez** [comment]
Also, this kind of changes should have been discussed first in a new issue, instead as part of a PR.

**Comment by mehdicopter** [comment]
You are right.
I'll close this and create an other PR just for templating then.
Thanks !

**Comment by eskombro** [comment]
Hi @mehdicopter !

Thanks for your contribution. Indeed it would be more interesting to have a discussion in an issue as @renehernandez  points out! But glad to see your interest, and always interested in any feedback!

FYI in MeiliSearch roadmap, the Core Team is working on [High Availability](https://roadmap.meilisearch.com/c/24-hight-availibility) which will enable us soon to have a consistent replication policy, and we will find the best way to fit this in Kubernetes!

**Pull request closed without merging**
