### PR TITLE
chore(statefulset): customizable initialDelaySeconds and periodSecond…

### PR DESCRIPTION
**Pull request by HelmutLety**
…s for livenessProbe and readinessProbe

- customize some values #29 
- Add those default values in the manifest

- Add the changes of #28 in the manifest

### CODE REVIEW

**Comment by HelmutLety** [comment]
Does the failing helm-test has something to do with #31 ?
Maybe you know @eskombro

**Comment by eskombro** [comment]
@HelmutLety Probably, let me check this

**Comment by eskombro** [comment]
bors try

**Comment by eskombro** [comment]
@HelmutLety 

Thanks for the patience! It was indeed caused by #31 and this problem is fixed now.

**Comment by HelmutLety** [comment]
Super nice, thanks @eskombro  !

**Comment by eskombro** [comment]
A pelasure!

Let me know when you feel everything is ready!

**Comment by HelmutLety** [comment]
I feel it is ready

**Comment by eskombro** [comment]
Thanks a lot for being so reactive and fast!

There have been some changes in master since you created the branch but I think this should create any conflict. 

Bors try

**Comment by eskombro** [comment]
This PR look good to me!

Thanks again @HelmutLety  !!!! 🎉

**Review by eskombro — APPROVED** [review]
👍🏽

**Comment by eskombro** [comment]
Bors merge

**Pull request merged**
