### PR TITLE
feat: allow other ingress class than Nginx

### PR DESCRIPTION
**Pull request by Tchoupinax**
# Pull Request

Hello :)

## What does this PR do?

I test the ingress recently fixed (thank you for that) but I can't use it with traefik because of the ingressClassName set as default to `nginx`.
I edited the chart to allow to dynamically change this value. :)

I set nginx as the default value but in my opinion not className should be the default value.

Anyway this improvement works for me.

Have a nice day!

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @Tchoupinax for this PR and for contributing to Meilisearch ❤️!
This is a great addition. You need to update the version in the `charts/meilisearch/Chart.yaml`

**Comment by Tchoupinax** [comment]
You right!
It is done :)

Have a nice day

**Review by alallema — APPROVED** [review]
LGTM! 🔥 🔥 🔥
Thanks @Tchoupinax for your contributions ❤️

**Comment by alallema** [comment]
bors merge

**Comment by Tchoupinax** [comment]
Thank you for your reactivity again!

**Pull request merged**
