### PR TITLE
change default to unset storageclass

### PR DESCRIPTION
**Pull request by acelinkio**
# Pull Request

## Related issue
N/A

## What does this PR do?
- Sets the default storageClass value to align with documentation beside it.  Requires one less variable be defined for a quick setup.

## PR checklist
Please check if your PR fulfills the following requirements:
- [X ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
I was not aware of the `~` tilde usage in YML, it means `null` right? 

And I think the change makes sense as well

**Comment by acelinkio** [comment]
correct.  ~ is shorthand for null. link to yaml source http://yaml.org/spec/1.2/spec.html#id2805071

**Comment by acelinkio** [comment]
I see the tests failed.  Looks like it expects a version to be bumped.  I am down to increment it, but figured that would be best to a release process.

**Comment by brunoocasali** [comment]
Hi @acelinkio can you update the chart version? So I can merge this PR?

**Comment by acelinkio** [comment]
Updated version to 0.9.1

**Review by brunoocasali — APPROVED** [review]

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
