### PR TITLE
Update to meilisearch 0.28.1

### LINKED ISSUE #129: Update to 0.28.1
**Description**
Helm chart is still pinned to 0.28.0 even though 0.28.1 has been released. (PR incoming)

**Expected behavior**
Helm chart to be updated.

**Current behavior**
Helm chart hasn't been updated.

### PR DESCRIPTION
**Pull request by Vashiru**
# Pull Request

## What does this PR do?
Fixes #129

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @Vashiru for this PR and for contributing to Meilisearch.
You also need to upgrade the version of the chart in this [file](https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/Chart.yaml)

**Comment by Vashiru** [comment]
@alallema Whoops, bumped it now.

**Comment by Vashiru** [comment]
@alallema Looks like you may have forgotten to approve the request? 😇

**Comment by alallema** [comment]
> @alallema Looks like you may have forgotten to approve the request? 😇

Hi @Vashiru,
Yes, sorry for the delay, I was quite busy the last few days.

**Review by alallema — APPROVED** [review]
LGTM! 🎉 
Thanks @Vashiru for contributing to Meilisearch ❤️

**Comment by alallema** [comment]
bors merge

**Pull request merged**
