### PR TITLE
Fix hard coded meilisearch-master-key ref in serviceMonitor

### PR DESCRIPTION
**Pull request by macropin**
# Pull Request

## What does this PR do?
- Fix hard coded meilisearch-master-key ref in serviceMonitor. The serviceMonitor was broken when the helm deployment name was changed from the default `meilisearch`. This also uses the existing template for all secretMasterKeyName usages which ensures consistency.

N.B. Please also consider fixing the language used in the application and this chart. "Master" is a dated and divisive term.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by macropin** [comment]
Linter is complaining about requiring a version bump. What do you want done here?

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
@meilisesarch sync-manifest

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
Hi @macropin you need to increase the version here:

https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/Chart.yaml#L5

**Review by brunoocasali — CHANGES_REQUESTED** [review]
Just fix the linter and we are good to go!

Thanks a lot for your contribution!

**Comment by macropin** [comment]
@brunoocasali It seems I don't have access to increment the release version.

**Comment by macropin** [comment]
@brunoocasali CI broken because of cosign deprecation Ref: https://blog.sigstore.dev/cosign-releases-bucket-deprecation/

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Comment by brunoocasali** [comment]
https://github.com/meilisearch sync-manifest

**Pull request merged**
