### PR TITLE
feat: reintroduce the possibility to specify a replicaCount in values.yaml

### PR DESCRIPTION
**Pull request by jlandic**
# Pull Request

## What does this PR do?
- Re-enable the possibility to customize the `spec.replicas` value of the StatefulSet, a requirement we have for our internal High Availability tests.
- Keep a default value of 1 replica to match the most common uses.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by alallema — APPROVED** [review]
Thanks for this PR @jlandic, and your first PR on this repo ✨ 
LGTM! 🔥

**Comment by alallema** [comment]
bors merge

**Comment by mike-code** [comment]
So just to confirm, even though it's a variable, it shouldn't be used?

**Comment by brunoocasali** [comment]
> So just to confirm, even though it's a variable, it shouldn't be used?
@mike-code Yes, you're right, Meilisearch is not highly available yet, so if you create more replicas you will end up with inconsistencies between the replica's data.

**Pull request merged**
