### PR TITLE
Fix Bug in ServiceMonitor

### PR DESCRIPTION
**Pull request by mike-stewart**
# Pull Request

## What does this PR do?
It appears there might be a bug in #153, as there should not be a dash in front of bearerTokenSecret. This is adding it as a second endpoint, when in fact it should be setting the bearerTokenSecret on the http endpoint.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]
bors merge

**Comment by mike-stewart** [comment]
@meilisearch sync-manifest

**Review by brunoocasali — APPROVED** [review]
bors merge

**Comment by brunoocasali** [comment]
Thank you @mike-stewart for your contribution! 🤘

**Pull request closed without merging**
