### PR TITLE
Support for specifying Nodeport in service

### PR DESCRIPTION
**Pull request by Thearas**
# Pull Request

## What does this PR do?

Implement #50.

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @Thearas for this PR!
You need to update the version in `charts/meilisearch/Chart.yaml`

**Comment by Thearas** [comment]
Done.

PTAL again @alallema.

**Review by alallema — APPROVED** [review]
LGTM!
Thanks for contributing to Meilisearch @Thearas

**Comment by alallema** [comment]
bors merge

**Pull request merged**
