### PR TITLE
Make replicas have 1 hardcoded

### LINKED ISSUE #188: Remove the possibility to set `replicaCount` to a value other than "1"?
According to various closed issues, Meilisearch does not support high availability when self-hosted, and using more than one replica can cause things to break.

That being said, should the `replicaCount` value be removed and just hard-code it to `1` for now?

https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/templates/statefulset.yaml#L8C39-L8C39

### PR DESCRIPTION
**Pull request by damieneichhorn**
# Pull Request

## Related issue
Fixes #188 

## What does this PR do?
- set replicaCount to a hardcoded 1
- remove replicaCount from default values file

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by brunoocasali — DISMISSED** [review]
Good for me @alallema

**Comment by damieneichhorn** [comment]
@meilisearch sync-manifest

**Comment by damieneichhorn** [comment]
@meilisearch sync-manifest

**Comment by damieneichhorn** [comment]
@brunoocasali it seems the sync-manifest command is erroring with the following error: `Request failed with error TypeError: Cannot read properties of undefined (reading 'get')`

**Comment by alallema** [comment]
Hi @damieneichhorn 
> @brunoocasali it seems the sync-manifest command is erroring with the following error: Request failed with error TypeError: Cannot read properties of undefined (reading 'get')

Yes, it's possible that the GitHub action doesn't work correctly for people who don't have rights on the repo. Sorry about that I allow myself to update the manifest

**Review by alallema — APPROVED** [review]
Thanks @damieneichhorn for this PR!
LGTM! But at the time I agreed with the issue I didn't have the information that the HA (High Availability) might be coming out soon. So I'm wondering if it's worth modifying the chart now.
I'll let @brunoocasali decide about it

**Comment by brunoocasali** [comment]
Let's merge it @alallema since we don't have a clear path of how our Meili version of the HA will look yet.

bors merge

**Pull request closed without merging**
