### PR TITLE
Document missing ingress.className value in README.md

### PR DESCRIPTION
**Pull request by c0bra**
# Pull Request

## What does this PR do?

The README.md is missing documentation of the `ingress.className` value.  If you mistakenly use an annotation like `kubernetes.io/ingress.class: nginx` you will get an error and scratch your head about how to address it.

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @c0bra for this PR and for contributing to Meilisearch ❤️ 
Good catch, by the way. Can you update the version of the package in `charts/meilisearch/Chart.file`? `0.1.48` should become `0.1.49`

**Comment by c0bra** [comment]
@alallema sure, done!

**Review by alallema — APPROVED** [review]
Thank you @c0bra
LGTM! ✨

**Comment by alallema** [comment]
bors merge

**Pull request merged**
