### PR TITLE
feat(meilisearch-kubernetes) Add ServiceAccount'

### PR DESCRIPTION
**Pull request by HelmutLety**
Add a ServiceAccount to the Application.
It allows us to identify meilisearch by it's service account token. Otherwise it will be assigned the default service account. This identity is also used by service meshes and vault for example. It is generally considered best practice to add a service account to all deployed services.

### CODE REVIEW

**Comment by eskombro** [comment]
@HelmutLety thanks a lot for this contribution!

I just want to comment on two things:
1. Do you think it is a good idea to use by default `{{ template "meilisearch.fullname" . }}` as the ServiceAccount name? Or maybe it shuld be specified in the `values` file so it can be set/modified by the user.
2. The filename has a typo, can you change it from `servicaccount.yaml` to `serviceaccount.yaml` ?

**Comment by HelmutLety** [comment]
Sorry for the typo, changed that :)
I used the the default Name, because it's what we also do for the other resources (Statefulset, PVC, SVC, ConfigMap). I don't see why not, but I can change it otherwise. Keeps the resource Names consistent

**Comment by renehernandez** [comment]
@HelmutLety There are two service account files being added. Can you remove the one with the typo **servicaccount.yaml**

**Comment by eskombro** [comment]
@HelmutLety Right, it's quite ok then! You should commit adding the file you want to delete because it is still en the repo as @renehernandez said!

I also see that the test fails to install the chart because apparently there is a namespace conflict, but I can't quite understand where this is coming from. Any ideas guys?

**Comment by eskombro** [comment]
Nevermind, checks are passing again ;)

**Comment by HelmutLety** [comment]
I made a new Commit to add the Labels

**Review by eskombro — APPROVED** [review]
Great! 👌

**Pull request merged**
