### PR TITLE
Fix indentation

### LINKED ISSUE #239: ServiceMonitor wrong indentation
**Description**
ServiceMonitor is defined in Helm chart in a way that makes it impossible to use `metricRelabelings` and `relabelings`.

**Expected behavior**
Correct indentation in generated ServiceMonitor yaml

**Current behavior**
Broken indentation in generated yaml

**Screenshots or Logs**
image

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: v1.10.0
- meilisearch-kubernetes version: 0.10.0

### PR DESCRIPTION
**Pull request by Vovcharaa**
Closes #239

### CODE REVIEW

**Review by brunoocasali — CHANGES_REQUESTED** [review]
Hey @Vovcharaa can you bump the meilisearch chart version to a patch? Then I can merge this improvement!

Thank you!

**Comment by Vovcharaa** [comment]
@brunoocasali Done

**Comment by brunoocasali** [comment]
@meilisearch sync-manifest

**Review by brunoocasali — APPROVED** [review]
bors merge

**Pull request merged**
