### PR TITLE
Update chart-testing-action

### PR DESCRIPTION
**Pull request by alallema**
Ci run with successful result but throw some error [here](https://github.com/meilisearch/meilisearch-kubernetes/runs/3530431818?check_suite_focus=true)
```
Warning: Unexpected input(s) 'command', 'config', valid inputs are ['version']
```
```
Building wheels for collected packages: yamale
  Building wheel for yamale (setup.py): started
  Building wheel for yamale (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/ct/v3.3.0/x86_64/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1u28dvlg/yamale/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1u28dvlg/yamale/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vet59bkm
       cwd: /tmp/pip-install-1u28dvlg/yamale/
  Running setup.py clean for yamale
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for yamale
Failed to build yamale
```

### CODE REVIEW

**Comment by eskombro** [comment]
@alallema  Do you have an example of an action that is run when changes are done to the Helm chart? all the jobs that I could found are skipping the chack since no changes were done to the chart itself ( maybe I'm wrong)

**Review by eskombro — COMMENTED** [review]
@alallema Do you have an example of an action that is run when changes are done to the Helm chart? all the jobs that I could found are skipping the chack since no changes were done to the chart itself ( maybe I'm wrong)

**Comment by alallema** [comment]
> @alallema Do you have an example of an action that is run when changes are done to the Helm chart? all the jobs that I could found are skipping the chack since no changes were done to the chart itself ( maybe I'm wrong)

No, your right it's because of this line:
`if: steps.list-changed.outputs.changed == 'true'`
But I wonder if it's not better if to remove it.

**Comment by eskombro** [comment]
Well, I think it is a good idea to have it because this CI is quite long, and if there are no changes for the Helm chart, there is no point in testing it. So it will make the flow faster. let's say you change the readme, you don't want to create a k8s cluster and test the Helm charts for that :)
But then I can not find an example of this new CI working

**Comment by alallema** [comment]
> Well, I think it is a good idea to have it because this CI is quite long, and if there are no changes for the Helm chart, there is no point in testing it. So it will make the flow faster. let's say you change the readme, you don't want to create a k8s cluster and test the Helm charts for that :)
> But then I can not find an example of this new CI working

Me too. You can check a complete CI [here](https://github.com/meilisearch/meilisearch-kubernetes/runs/3542691271?check_suite_focus=true)

**Review by eskombro — APPROVED** [review]
Thanks! But it is still the case in which there are no changes to the chart, but we can see the cluster being created and everything seems ok. We will probably need to see when the chart is modified if everything is ok

Screenshot 2021-09-08 at 11 27 07

🎉

**Comment by alallema** [comment]
> Thanks! But it is still the case in which there are no changes to the chart, but we can see the cluster being created and everything seems ok. We will probably need to see when the chart is modified if everything is ok
> 
> Screenshot 2021-09-08 at 11 27 07
> 
> 🎉

Damn! You are so right I hope it will be ok

**Comment by alallema** [comment]
bors merge

**Pull request merged**
