### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by eskombro**
Add .editorconfig to guarantee harmony on `yaml` and `md` files

@curquiza And the newline I owed to you ;)

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
See https://github.com/meilisearch/meilisearch-kubernetes/pull/36 🙂
(you can merge #36 if you agree of course)

**Comment by eskombro** [comment]
bors merge

**Comment by eskombro** [comment]
@curquiza Yep, indeed, as long as there is any diff in the Chart files, CI wont accept that you don't update the version, and I think this is a good thing even if sometimes it creates situations as absurd as this one. Thanks for your PR. I modified the Chart version, and neer your review, but feel free to merge too if you approve

**Comment by eskombro** [comment]
bors try

**Review by curquiza — APPROVED** [review]
Wonderful!!

**Comment by eskombro** [comment]
bors merge

**Pull request merged**
